#-------------------------------
# Site Settings
title: Rui Sun's Homepage
logo: # You can add own logo. For example '/images/logo.png'.
description: Rui Sun's homepage.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Publications'
      url: '/publications/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Product'
      url: '/product/'
    - title: 'Talks'
      url: '/talks/'
    - title: 'Teaching'
      url: '/teaching/'
    - title: 'Awards'
      url: '/awards/'
    - title: 'Media'
      url: '/media/'
    - title: 'CV'
      url: '/cv/'
    - title: 'Contact'
      url: '/contact/'


#-------------------------------
# Author Settings
author:
  author__name: Rui Sun
  author__bio: Hi, I'm a PhD student at Newcastle University (UK) supervised by Prof. Rajiv Ranjan. Also, I have three years of experience working in industry.
  author__avatar: '/images/my_photo.jepg'

social:
- {icon: "ion-logo-linkedin", link: "https://facebook.com"}
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-github", link: "https://github.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: Rui Sun
  hero__description: PhD Student at Newcastle University, UK.
  hero__image: "/images/01-1.jpg"


#-------------------------------
# Logos Settings
logos:
  enable: true
  logos__title: I’ve worked with some great сompanies

logo__items:
  - name: Newcastle University
    link: "https://www.ncl.ac.uk/"
    image: "/images/company_logos/Newcastle_University_logo.png"

  - name: Shanghai Electric
    link: "https://www.shanghai-electric.com/group_en/"
    image: "/images/company_logos/shanghai-electric-logo.png"

  - name: FLock.io
    link: "https://flock.io/#/"
    image: "/images/company_logos/flock-io-logo.png"

#-------------------------------
# Newsletter
#mailchimp:
#  enable: true
#  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
#  mailchimp__input__text: Your email address...
#  mailchimp__button__text: Subscribe


#-------------------------------
# Work Settings
#work:
#  enable: true
#  work__title: Work
#  work__description: I shows only the best websites and portfolios built completely with passion, simplicity & creativity!


#-------------------------------
# Testimonials Section
#testimonials:
#  enable: true
#
#testimonial__title: Clients
#testimonial__description:
#
#testimonial__items:
#  - name: "Hanna Septimus"
#    image: "/images/client-1.jpg"
#    designation: "Product Designer"
#    link: "https://twitter.com/"
#    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
#
#  - name: "Carla Rosser"
#    image: "/images/client-2.jpg"
#    designation: "Statistician"
#    link: "https://facebook.com/"
#    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
#
#  - name: "Maria Curtis"
#    image: "/images/client-3.jpg"
#    designation: "Team Lead"
#    link: "https://twitter.com/"
#    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
#
#  - name: "Carter Bergson"
#    image: "/images/client-4.jpg"
#    designation: "CEO, Founder"
#    link: "https://facebook.com/"
#    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
#
#  - name: "Jordyn Franci"
#    image: "/images/client-5.jpg"
#    designation: "Personal Trainer"
#    link: "https://twitter.com/"
#    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
#
#  - name: "Mira Carder"
#    image: "/images/client-6.jpg"
#    designation: "Data Scientist"
#    link: "https://facebook.com/"
#    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
#
#  - name: "Madelyn Herwitz"
#    image: "/images/client-7.jpg"
#    designation: "Frontend Engineer"
#    link: "https://twitter.com/"
#    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
#
#  - name: "Anika Schleifer"
#    image: "/images/client-8.jpg"
#    designation: "Fitness Director"
#    link: "https://facebook.com/"
#    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
#
#  - name: "Wilson Dorwart"
#    image: "/images/client-9.jpg"
#    designation: "Financial Manager"
#    link: "https://twitter.com/"
#    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"


#-------------------------------
# Blog Section
blog:
  enable: false

blog__settings:
  blog__title: Writing
  blog__description:


#-------------------------------
# Footer Settings
footer__background__image: "/images/footer.jpeg"

#-------------------------------
# Contact Settings
contact:
  email: ray.ruisun@qq.com # Add your form_id
  description: contact. # Add a description of your form

# NOTE
# Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id